# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ca8dd3f6c57426cc8470b65fb61829220731995d802d13795f2628ecd697a7e1d6c3078b9e04b3c627ff16b1258527cb4c096cea7bd16096236c27c3b163f77

test:
  secret_key_base: e967197ded7a6a8280acf3980a6f04765cb3073860336dd99e35e1aea6c913d5aaded61943323e16c35c1e784adfbfedf4a494963e391132f9158c46f84f2fc4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
